### ISSUE TITLE
Error when trying to install in Matlab R2013B

### ISSUE THREAD

**Issue by odemo** [CATIA-Systems/FMIKit-Simulink#73]
I get the following error message when running the FMIKit-2.6.mlappinstall for Matlab R2013B:
java.lang.NumberFormatException: For input string: "Simulink"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at com.mathworks.appmanagement.AppMetadataImpl.getRequiredProducts(AppMetadataImpl.java:147) at com.mathworks.appmanagement.AppManagementApiImpl.checkProductDependencies(AppManagementApiImpl.java:291) at com.mathworks.appmanagement.AppManagementApiImpl.install(AppManagementApiImpl.java:87) at com.mathworks.appmanagement.AppManagementApiImpl$1.run(AppManagementApiImpl.java:68)   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by t-sommer** [comment]
This seems to be a bug in R2013b. As a workaround, you can extract the `*.mlappinstall` file with [7zip](https://www.7-zip.org/), put the folder on the MATLAB path and run `FMIKit.initialize()`.

**Comment by odemo** [comment]
Hi,

Thank you for the feedback. However I am not able to choose the grtfmi.tlc file in the System target file browser, because it is not listed there. What do I do wrong?

Best regards,
Odd Erik
